#!/usr/bin/env bash

# custom-hook

pattern="(JIRA|PROJECTKEY)\-[0-9]"
check=$(grep -E "${pattern}" "${1}")

if [[ "${check}" != "" ]]; then
  # Everything is OK
	exit 0
else
  # No match, fail hard
	echo "Invalid commit message, commit message should contain project key and issue key separated by a dash. e.g. JIRA-123"
	exit 1
fi
